title: qainsights-jmeter
description: qainsights-jmeter
template:
  repo: qainsights-jmeter-template
  name: qainsights-jmeter
  description: testimg
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: "erere"
    description: welcome
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
