title: qainsights-jmeter
description: qainsights-jmeter
template:
  repo: qainsights-jmeter-template
  name: qainsights-jmeter
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        issue: 1
        with: questions/01.md
      - type: createIssue
        title: TG
        body: issues/01.md
